class PublicKey:
    def __init__(self, public_key: str) -> None: ...
    def blind(self, msg: bytes, randomize_message: bool) -> tuple[bytes, bytes, bytes]: ...
    def finalize(self, blind_sig: bytes, secret: bytes, msg_randomizer: bytes | None, msg: bytes) -> bytes: ...
    def verify(self, sig: bytes, msg: bytes, msg_randomizer: bytes | None) -> bool: ...

class SecretKey:
    def __init__(self, secret_key: str) -> None: ...
    def sign(self, blind_msg: bytes) -> bytes: ...
